[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.4.1", features = ["csr","nightly"] }
rand = "0.8.5"
getrandom = {version = "0.2.9", features = ["js"]}
nanoid = "0.4.0"